/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/56615 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=120313375 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Puccinia_graminisug99.v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pucgr2_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_PgraminisCRL75-36-700-3_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/62688 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=126561138 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Blumeria_graminis.EF2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Blugr2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/222929 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=27461610 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coccidioides_posadasii_c735_delta_sowgp.JCVI-cpa1-1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CposadasiiC735deltSOWgp_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/237561 -p 2_contributing_databases_ENSEMBLE_ENSEMBLE_1K genomeSize=15465468 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Candida_albicans_sc5314.Cand_albi_SC5314_V4.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Candida_albicans_sc5314_gca_000784655.Cand_albi_SC5314_V3.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Canalb1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/246409 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=46913509 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Rhizopus_delemar_ra_99_880.RO3.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_RdelemarRA99-880_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/246410 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=29430390 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coccidioides_immitis_rs.ASM14933v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cocim1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CimmitisRS_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/294746 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=10762497 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Meyerozyma_guilliermondii_atcc_6260.ASM14942v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Meygui1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/294750 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=17729388 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cryptococcus_gattii_vgii_r265.CNB2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CdeuterogattiiR265_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/306901 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=35580791 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Chaetomium_globosum_cbs_148_51.ASM14336v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Chagl_1_assembly_scaffolds_repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/306902 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=12297546 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Clavispora_lusitaniae_atcc_42720.ASM383v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Clalu1_2_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_ClusitaniaeATCC42720_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/331117 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=32298558 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Neosartorya_fischeri.ASM14964v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AfischeriNRRL181_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/332952 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=37507265 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_flavus.JCVI-afl1-v2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AflavusNRRL3357_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/336963 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=22699644 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Uncinocarpus_reesii_1704.ASM351v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Uncre1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Ureesii1704_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/339724 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=33580120 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Histoplasma_capsulatum_nam1.ASM14958v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Hisca1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_HcapsulatumNAm1_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/341663 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=29905486 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_terreus.ASM14961v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspte1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AterreusNIH2624_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/344612 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=28323724 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_clavatus.ASM271v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AclavatusNRRL1_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/379508 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=15765543 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Lodderomyces_elongisporus_nrrl_yb_4239.ASM14968v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Lodelo1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/380704 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=35419824 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_niger_atcc_1015.ASPNI_v3.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AnigerATCC1015_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/396776 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=28243688 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coccidioides_immitis_h538_4.ASM14981v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CimmitisH538-4_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/402676 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=11928704 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Schizosaccharomyces_japonicus.GCA_000149845.2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Schja1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_SjaponicusyFS275_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/403673 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=24117777 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Batrachochytrium_dendrobatidis_jel423.BD_JEL423.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_BdendrobatidisJEL423_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/404692 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=29388124 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coccidioides_immitis_rmscc_2394.ASM14989v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CimmitisRMSCC2394_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/413071 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=39668592 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichoderma_virens.ASM17099v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Trichoderma_virens_v2.allmasked useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/431241 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=34121661 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichoderma_reesei.GCA_000167675.2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Trichoderma_reeseiV2.allmasked /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_TreeseiQM6a_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/441959 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=36280080 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Talaromyces_stipitatus_atcc_10500.JCVI-TSTA1-3.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_TstipitatusATCC10500_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/441960 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=29121456 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Talaromyces_marneffei_atcc_18224.JCVI-PMFA1-2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_TmarneffeiATCC18224_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/443226 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=28036638 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coccidioides_posadasii_str_silveira.CPS2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CposadasiiSilveira_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/447093 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=30988936 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Histoplasma_capsulatum_g186ar.ASM15011v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_HcapsulatumG186AR_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/451804 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=29691090 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_fumigatusa1163.ASM15014v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AfumigatusA1163_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/452589 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=36742855 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichoderma_atroviride_imi_206040.TRIAT_v2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Trichoderma_atroviride_v2.allmasked useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/454284 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=28666980 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coccidioides_posadasii_rmscc_3488.ASM15005v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CposadasiiRMSCC3488_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/454286 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=28167963 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coccidioides_immitis_rmscc_3703.ASM15008v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CimmitisRMSCC3703_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/481877 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=3923493 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Enterocytozoon_bieneusi_h348.ASM20948v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Entbi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/482561 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=29544190 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Paracoccidioides_brasiliensis_pb03.Paracocci_br_Pb03_V2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_PbrasiliensisPb03_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/483514 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=11828380 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Schizosaccharomyces_octosporus.GCA_000150505.2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Schoc1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_SoctosporusyFS286_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/500485 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=32759734 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Penicillium_rubens_wisconsin_54_1255.PenChr_Nov2007.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_PrubensWisconsin54-1255_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/502779 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=33469040 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Paracoccidioides_sp_lutzii_pb01.Paracocci_br_Pb01_V2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_PlutziiPb01_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/502780 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=30449457 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Paracoccidioides_brasiliensis_pb18.Paracocci_br_Pb18_V2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Parbra1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_PbrasiliensisPb18_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/510951 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=39796677 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Neurospora_tetrasperma_fgsc_2508.v2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_NtetraspermaFGSC2508_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/510952 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=39908772 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Neurospora_tetrasperma_fgsc_2509.v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Neurospora_tetrasperma_mata.allmasked useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/510953 -p 2_contributing_databases_1K_FUNGIDB genomeSize=38046976 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/1K/Neurospora_discreta.allmasked /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_NdiscretaFGSC8579_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/544711 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=38535584 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Histoplasma_capsulatum_h88.ASM15100v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_HcapsulatumH88_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/544712 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=39571296 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Histoplasma_capsulatum_h143.ASM15103v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_HcapsulatumH143_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/554155 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=23621856 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Arthroderma_otae_cbs_113480.ASM15114v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Micca1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/554373 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=27110592 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Moniliophthora_perniciosa_fa553.ASM18302v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Monpe1_1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/559298 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=76659295 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Blastomyces_gilchristii_slh14081.BD_SLH14081_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Blade1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/559305 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=22874390 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichophyton_rubrum_cbs_118892.ASM15142v1.dna_sm.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Triru1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/578456 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=29204505 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Tremella_mesenterica_dsm_1558.Treme1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Treme1_masked_genomic_scaffolds.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_TmesentericaDSM1558_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/578457 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=43585632 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Serpula_lacrymans_var_lacrymans_s7_9.v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/SerlaS7_9_2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/578459 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=21433230 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Rhodotorula_graminis_wp1.Rhoba1_1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Rhoba1_1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/578462 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=58011572 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Allomyces_macrogynus_atcc_38327.A_macrogynus_V3.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Allma1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AmacrogynusATCC38327_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/590646 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=10959525 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/_candida_tenuis_atcc_10573.Candida_tenuis_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cante1_masked_genomic_scaffolds.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/597362 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=33266016 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Agaricus_bisporus_var_burnettii_jb137_s8.Agabi_varbur_1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Abisporus_varburnettii.v2.masked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/602072 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=37015794 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_carbonarius_item_5010.Aspca3.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspca3_masked_scaffolds.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AcarbonariusITEM5010_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/619300 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=12576928 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Spathaspora_passalidarum_nrrl_y_27907.Spathaspora_passalidarum_v2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Spapa3_masked_genomic_scaffolds.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/630390 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=165661209 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Puccinia_triticina.ASM15152v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Puctr1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/644352 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=44497673 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Gaeumannomyces_graminis.Gae_graminis_V2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Gaegr1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/645133 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=52503120 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Colletotrichum_graminicola.C_graminicola_M1_001_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Colgr1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/645134 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=24529152 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Spizellomyces_punctatus_daom_br117.S_punctatus_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Spipu1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_SpunctatusDAOMBR117_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/653667 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=11746800 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Schizosaccharomyces_cryophilus.GCA_000004155.2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Schcy1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/655819 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=34258350 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Beauveria_bassiana_arsef_2860.ASM28067v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Beaba1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/655827 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=40078300 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Metarhizium_acridum_cqma_102.MetAcr_May2010.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Metac1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/655844 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=42349860 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Metarhizium_anisopliae_arsef_23.MAA_2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Metro1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/656061 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=127024884 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Tuber_melanosporum.ASM15164v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Tubme1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/658429 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=36323456 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Pseudogymnoascus_destructans_20631_21.Geom_destructans_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pseudest1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/660027 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=50491312 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fusarium_oxysporum_fo47.FO_Fo47_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_FoxysporumFo47_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/663202 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=22913153 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichophyton_verrucosum_hki_0517.ASM15150v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Triver1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/663331 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=22590756 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichophyton_benhamiae_cbs_112371.ASM15112v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Artbe1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/664439 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=59464580 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Paxillus_involutus_atcc_200175.Paxillus_involutus_ATCC_200175_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Paxin1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/665079 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=38969136 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Sclerotinia_sclerotiorum.ASM14694v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Sclsc1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Ssclerotiorum1980UF-70_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/665912 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=35103787 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Bipolaris_sorokiniana_nd90pr.Cocsa1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cocsa1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/669874 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=12848616 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Pachysolen_tannophilus_nrrl_y_2460.Pacta1_2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pacta1_2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/670483 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=37923458 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Gloeophyllum_trabeum_atcc_11539.Glotr1_1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Glotr1_1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/671144 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=10009776 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Wallemia_mellicola_cbs_633_66.Wallemia_sebi_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Walse1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/675120 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=30811300 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Dothistroma_septosporum.GCA_000340195.1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Dotse1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/683840 -p 2_contributing_databases_ENSEMBLE_1K_1K genomeSize=26573597 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Microbotryum_violaceum.GCA_000166175.1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Micld1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/1K/Micvi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/684364 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=24799671 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Batrachochytrium_dendrobatidis_jam81.v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Batde5_masked_scaffolds.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/685588 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=60604632 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Galerina_marginata_cbs_339_88.Galma1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Galma1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/686832 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=38989456 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Hebeloma_cylindrosporum_h7.Hebeloma_cylindrosporum_h7_v2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Hebcy2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/690307 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=36132360 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_aculeatus_atcc_16872.Aspac1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspac1_masked_scaffolds.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AaculeatusATCC16872_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/692275 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=29937096 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Sphaerulina_musiva_so2202.Septoria_musiva_SO2202_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Sepmu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/694068 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=64620180 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fomitiporia_mediterranea_mf3_22.Fomme1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Fomme1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/698492 -p 2_contributing_databases_ENSEMBLE_ENSEMBLE_1K genomeSize=14404705 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Saitoella_complicata_nrrl_y_17804_gca_001661265.Saico1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Saitoella_complicata_nrrl_y_17804.Scomplicata_3.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Saico1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/701091 -p 2_contributing_databases_ENSEMBLE_1K_1K genomeSize=37148536 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Bipolaris_maydis_c5.CocheC5_3.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/CocheC5_1_assembly_scaffolds_repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/1K/CocheC5_3_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/717646 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=22311871 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Baudoinia_panamericana_uamh_10762.Bauco1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Bauco1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/717944 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=45687803 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trametes_versicolor_fp_101664_ss1.Trametes_versicolor_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Trave1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/721885 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=47439876 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Stereum_hirsutum_fp_91666_ss1.Stehi1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Stehi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/732165 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=43601190 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Dichomitus_squalens_lyad_421_ss1.Dichomitus_squalens_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Dicsq1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/741275 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=34853325 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Punctularia_strigosozonata_hhb_11173_ss5.Punctularia_strigosozonata_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Punst1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/741705 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=43825950 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coniophora_puteana_rwd_64_598_ss2.Conpu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Conpu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/745531 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=30746034 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Phlebiopsis_gigantea_11061_1_cr5_6.Phlgi1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Phlgi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/747089 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=92915025 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Rhizophagus_irregularis_daom_181602_gca_000439145.Gloin1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Gloin1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/747525 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=34314720 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Heterobasidion_irregulare_tc_32_1.Heterobasidion_irregulare_v2.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Heterobasidion_annosum.allmasked useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/747676 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=102813480 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Melampsora_laricipopulina.GCA_000204055.1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Mlarici-populina98AG31_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/747725 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=37194482 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Mucor_circinelloides_f_lusitanicus_cbs_277_49.Mucci2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_McircinelloidesCBS277-49_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/756982 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=40738630 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Arthrobotrys_oligospora_atcc_24927.AOL24927_1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Artol1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/763406 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=11813791 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Pichia_membranifaciens_nrrl_y_2026.Picme2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Picme2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/763407 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=54835120 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Phycomyces_blakesleeanus_nrrl_1555_.Phybl2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_PblakesleeanusNRRL1555_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/765440 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=60512595 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Piloderma_croceum_f_1598.Piloderma_croceum_F_1598_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pilcr1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/767744 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=9359880 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Tortispora_caseinolytica_nrrl_y_17796.Canca1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Canca1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/767769 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=36523935 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_brasiliensis_cbs_101740.Aspbr1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspbr1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AbrasiliensisCBS101740_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/767770 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=35847570 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_tubingensis_cbs_134_48.Asptu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Asptu1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AtubingensisCBS134.48_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/771870 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=40441374 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Sordaria_macrospora.ASM18280v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Smacrosporak-hell_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/796925 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=40700100 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Conidiobolus_coronatus_nrrl_28638.Conidiobolus_coronatus_NRRL28638.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Conco1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/857340 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=29039040 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Acremonium_chrysogenum_atcc_11550.ASM76926v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Acrchr1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/857566 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=14020820 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Nadsonia_fulvescens_var_elongata_dsm_6958.Nadfu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Nadfu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/858893 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=26783210 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Exophiala_dermatitidis_nih_ut8656.Exop_derm_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Exode1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/869754 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=16374240 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Metschnikowia_bicuspidata_var_bicuspidata_nrrl_yb_4993.Metbi1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Metbi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/875184 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=65854746 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Puccinia_striiformis.PST-130_1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pucst1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/881290 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=4138680 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Nematocida_parisii_ertm1.Nema_parisii_ERTm1_V3.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Nempa1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/913774 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=47352700 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Oidiodendron_maius_zn.Oidiodendron_maius_Zn_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Oidma1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/914234 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=39749100 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Gelatoporia_subvermispora_b.Ceriporiopsis_subvermispora_B_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Ceriporiopsis_subvermispora.masked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/930089 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=31892228 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Bipolaris_zeicola_26_r_13.Cochliobolus_carbonum_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cocca1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/930090 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=31988063 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Bipolaris_oryzae_atcc_44560.Cochliobolus_miyabeanus_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cocmi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/930091 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=33484984 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Bipolaris_victoriae_fi3.Cochliobolus_victoriae_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cocvi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/930990 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=47605688 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Botryobasidium_botryosum_fd_172_ss1.Botbo1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Botbo1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/930992 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=45119542 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Suillus_luteus_uh_slu_lm8_n1.Suilu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Suilu4_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/933084 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=45944775 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Jaapia_argillacea_mucl_33604.Jaaar1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Jaaar1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/933388 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=30653523 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Penicillium_oxalicum_114_2.pde_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Penox1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/933852 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=38854998 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Serendipita_vermifera_maff_305830.Sebacina_vermifera_MAFF_305830_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Sebve1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/936435 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=47984272 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Serpula_lacrymans_var_lacrymans_s7_3.v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Serpula_lacrymans_S7_3_v2.masked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/944288 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=35186284 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Plicaturopsis_crispa_fd_325_ss_3.Plicr1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Plicr1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/944289 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=67605245 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Gymnopus_luxurians_fd_317_m1.Gymlu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Gymlu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/945553 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=48991360 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Hypholoma_sublateritium_fd_334_ss_4.Hypsu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Hypsu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/946122 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=41513205 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Amanita_muscaria_koide_bx008.Amanita_muscaria_Koide_BX008_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Amamu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/983644 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=32805344 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cordyceps_militaris_cm01.CmilitarisCM01_v01.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cormi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/983966 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=13277732 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cyberlindnera_jadinii_nrrl_y_1542.Cybja1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cybja1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/983967 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=13497710 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Candida_arabinofermentans_nrrl_yb_2248.Canar1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Canar1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/984485 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=12650013 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Hyphopichia_burtonii_nrrl_y_1933.Hypbu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Hypbu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/984486 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=15524082 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Babjeviella_inositovora_nrrl_y_12698.Babin1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Babin1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/984487 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=13397568 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Candida_tanzawaensis_nrrl_y_17324.Canta1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Canta1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/988480 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=12056715 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Rozella_allomycis_csf55.Rozella_k41_t100.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Rozal1_1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/994086 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=39043647 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Hydnomerulius_pinastri_md_312.Hydpi2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Hydpi2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1028729 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=37547496 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fusarium_pseudograminearum.GCA_000303195.1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Fusps1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1033177 -p 2_contributing_databases_1K_FUNGIDB genomeSize=37697604 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/1K/Aspka1_1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AkawachiiIFO4308_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1036611 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=33788061 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_versicolor_cbs_583_65.Aspve1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspve1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AversicolorCBS583.65_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1036612 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=35067537 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_sydowii_cbs_593_65.Aspsy1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspsy1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AsydowiiCBS593.65_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1036808 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=57266776 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Scleroderma_citrinum_foug_a.Scleroderma_citrinum_Foug_A_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Sclci1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1037660 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=19014755 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Tilletiaria_anomala_ubc_951.Tilletiaria_anomala_UBC_951_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Tilan2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1043003 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=26726400 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aureobasidium_melanogenum_cbs_110374.Aureobasidium_pullulans_var._melanogenum_CBS_110374_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aurpu_var_mel1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1043004 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=25934882 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aureobasidium_namibiae_cbs_147_97.Aureobasidium_pullulans_var._namibiae_CBS_147.97_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aurpu_var_nam1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1043005 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=26311425 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aureobasidium_subglaciale_exf_2481.Aureobasidium_pullulans_var._subglaciale_EXF-2481_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aurpu_var_sub1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1051891 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=63639450 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Tulasnella_calospora_mut_4182.Tulasnella_calospora_AL13_4D_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Tulca1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1069443 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=42546350 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Mortierella_verticillata_nrrl_6337.Mort_vert_NRRL_6337_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Morve1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1072389 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=52814647 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Marssonina_brunnea_f_sp_multigermtubi_mb_m1.ASM29877v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Marbr1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1073089 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=31976478 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_wentii_dto_134e9.Aspwe1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspwe1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AwentiiDTO134E9_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1073090 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=29501680 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Penicilliopsis_zonata_cbs_506_65.Aspzo1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspzo1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AzonataCBS506.65_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1076935 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=50858876 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Pyronema_omphalodes_cbs_100304.Pcon_v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pyrco1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1089451 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=47328468 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fusarium_oxysporum_f_sp_cubense_tropical_race_4_54006.FO_II5_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Foxysporum54006_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1089452 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=54933510 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fusarium_oxysporum_f_sp_melonis_26406.FO_melonis_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Foxysporum26406_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1095629 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=53331744 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Laccaria_amethystina_laam_08_1.Laccaria_amethystina_LaAM-08-1_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Lacam2_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1108050 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=49325760 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Rhizoctonia_solani_ag_1_ib.ASM35025v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Rhiso1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1109443 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=25479216 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Serendipita_indica_dsm_11827.ASM31354v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pirin1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1126212 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=49698000 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Macrophomina_phaseolina_ms6.MphMS6_1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Macph1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1128425 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=34520304 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fistulina_hepatica_atcc_64428.Fishe1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Fishe1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1130832 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=20559962 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Rhodotorula_toruloides_np11.RHOziaDV1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Rhoto1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1137138 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=34743528 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Pleurotus_ostreatus_pc15.PleosPC15_2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/PleosPC15_2_Assembly_scaffolds_repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1137211 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=38216548 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_luchuensis_cbs_106_47.Aspfo1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspfo1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AluchuensisCBS106.47_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1160497 -p 3_contributing_databases_ENSEMBLE_1K_FUNGIDB genomeSize=28552072 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_glaucus_cbs_516_65.Aspgl1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspgl1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AglaucusCBS516.65_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1165861 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=119261340 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Puccinia_striiformis_f_sp_tritici_pst_78.P_striiformis_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pucst_PST78_1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1168221 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=29121404 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Coniosporium_apollinis_cbs_100218.Coni_apol_CBS100218_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Conap1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1170230 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=26485319 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Penicillium_digitatum_pd1.PdigPd1_v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pendig1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1182541 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=26236606 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Capronia_coronata_cbs_617_96.Capr_coro_CBS_617_96_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Capcor1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1182542 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=29370006 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Capronia_epimyces_cbs_606_96.Capr_epim_CBS_606_96_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Capep1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1182543 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=40076106 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cladophialophora_psammophila_cbs_110553.Clad_psam_CBS_110553_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Claps1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1182544 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=28348176 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cladophialophora_yegresii_cbs_114405.Clad_yegr_CBS_114405_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Claye1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1182545 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=42258709 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Exophiala_aquamarina_cbs_119918.Exop_aqua_CBS_119918_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Exoaq1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1186058 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=24675101 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichosporon_asahii_var_asahii_cbs_2479.Trichosporon_asahii_1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Trias2479_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1220162 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=25686177 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Trichosporon_asahii_var_asahii_cbs_8904.ASM29921v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Trias8904_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1220924 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=29258594 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cyphellophora_europaea_cbs_101466.Phia_euro_CBS_101466_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Cypeu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1227346 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=45961568 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fusarium_proliferatum_et1.F._proliferatum_ET1_version_1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_FproliferatumET1_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1229664 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=48451671 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fusarium_oxysporum_f_sp_cubense_race_1.Foc1_1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Foxysporumrace1_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1229665 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=53807880 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fusarium_oxysporum_f_sp_cubense_race_4.Foc4_1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Foxysporumrace4_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1230383 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=7797010 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Malassezia_sympodialis_atcc_42132.ASM34930v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Malsy1_1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1263415 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=37747376 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Endocarpon_pusillum_z07020.EPUS.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/EndpusZ1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1268274 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=161592584 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Blumeria_graminis_f_sp_tritici_96224.Bgt_454_newbler_assembly.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Blugra1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1279043 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=29473047 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cladophialophora_carrionii_cbs_160_54.Clad_carr_CBS_160_54_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Claca1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1284197 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=40190017 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Dactylellina_haptotyla_cbs_200_50.MHA_v2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Monha1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1286976 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=48256416 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Phaeoacremonium_minimum_ucrpa7.UCRPA7V03.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Phaal1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1287680 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=43302939 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Neofusicoccum_parvum_ucrnp2.UCRNP2V3.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Neopa1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1287681 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=54905016 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Eutypa_lata_ucrel1.UCREL1V03.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Eutla1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1296103 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=17964528 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cryptococcus_gattii_ejb2.Cryp_gatt_EJB2_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CgattiiEJB2_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1296105 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=17941732 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cryptococcus_gattii_vgiv_ind107.Cryp_gatt_IND107_V2.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CgattiiIND107_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1296108 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=18331990 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cryptococcus_gattii_nt_10.Cryp_gatt_NT-10_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CgattiiNT10_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1296111 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=17727402 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cryptococcus_gattii_ca1873.Cryp_gatt_CA1873_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_CgattiiCA1873_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1299270 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=9815564 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Wallemia_ichthyophaga_exf_994.Wallemia_ichthyophaga_version_1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Walic1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1305764 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=18750194 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Pseudozyma_hubeiensis_sy62.ASM40351v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Psehu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1314777 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=35949460 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Sistotremastrum_niveocremeum_hhb9708.Sisni1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Sisni1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1314782 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=36352075 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Neolentinus_lepideus_hhb14362_ss_1.Neole1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Neole1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1314783 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=33389853 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Daedalea_quercina_l_15889.Daequ1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Daequ1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1314785 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=40714284 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Laetiporus_sulphureus_93_53.Laesu1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Laesu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1314800 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=36703590 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Rhizopogon_vinicolor_am_or11_026.Rhivi1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Rhivi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1328760 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=24742152 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Xylona_heveae_tc161.Xylona_heveae_TC161_v1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Xylhe1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1330018 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=29581220 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Calocera_viscosa_tufc12733.Calvi1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Calvi1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1344418 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=17853066 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Ascoidea_rubescens_dsm_1968.Ascru1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Ascru1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1353952 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=33908810 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Calocera_cornea_hhb12733.Calco1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Calco1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1356009 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=30257955 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Byssochlamys_spectabilis_no_5.PVAR5_assembly01.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Byssp1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1380566 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=44845682 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Pochonia_chlamydosporia_170.ASM165323v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Pocchl1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1382522 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=10412269 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Kuraishia_capsulata_cbs_1993.AUH_PRJEB4427_v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Kurca1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1388766 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=26732420 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_ruber_cbs_135680.Eurhe1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Eurhe1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1391700 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=18219264 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Moesziomyces_aphidis_dsm_70725.PseuAph1.0.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Moeaph1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1392248 -p 2_contributing_databases_1K_FUNGIDB genomeSize=28727700 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/1K/Aspcam1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AcampestrisIBT28561_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1392250 -p 2_contributing_databases_1K_FUNGIDB genomeSize=38477632 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/1K/Aspste1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AsteyniiIBT23096_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1392255 -p 2_contributing_databases_1K_FUNGIDB genomeSize=32977862 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/1K/Aspnov1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AnovofumigatusIBT16806_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1392256 -p 2_contributing_databases_1K_FUNGIDB genomeSize=28179132 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/1K/Aspoch1_AssemblyScaffolds_Repeatmasked.fasta /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_AochraceoroseusIBT24754_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1397361 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=32883540 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Sporothrix_schenckii_1099_18.S_schenckii_v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Sschenckii1099-18_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1398154 -p 2_contributing_databases_ENSEMBLE_FUNGIDB genomeSize=33714804 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Sporothrix_brasiliensis_5110.S_brasiliensis_5110_v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/FUNGIDB/FungiDB-41_Sbrasiliensis5110_Genome.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1442368 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=35265945 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fonsecaea_pedrosoi_cbs_271_37.Fons_pedr_CBS_271_37_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Fonpe1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1442370 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=37332960 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Cladophialophora_bantiana_cbs_173_52.Clad_bant_CBS_173_52_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Claba1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1442371 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=34003505 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Fonsecaea_multimorphosa_cbs_102226.Fons_mult_CBS_102226_V1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Fonmu1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
/u/home/a/akarlsbe/scratch/canu-1.8/*/bin/canu -d /u/home/a/akarlsbe/scratch/strain_contig_only_assemblies/1509407 -p 2_contributing_databases_ENSEMBLE_1K genomeSize=36740834 -nanopore-raw /u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Aspergillus_nomius_nrrl_13137.ASM120477v1.dna.toplevel.fa /u/home/a/akarlsbe/scratch/fungi/1K/Aspnom13137_1_AssemblyScaffolds_Repeatmasked.fasta useGrid=false stopOnLowCoverage=2
